### ISSUE TITLE
Add support for matplotlib 3.9

### ISSUE THREAD

**Issue by keithchev** [Arcadia-Science/arcadia-pycolor#27]
There are several breaking changes in 3.9 including the removal of `matplotlib.pyplot.register_cmap` and `cm.get_cmap`. See [here](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#top-level-cmap-registration-and-access-functions-in-mpl-cm).

**Comment by mezarque** [comment]
Resolved by #32
