### ISSUE TITLE
"Inner" plot is suppressed or hidden for seaborn violin plots

### ISSUE THREAD

**Issue by lanery** [Arcadia-Science/arcadia-pycolor#42]
### MWE
```python
import arcadia_pycolor as apc
import seaborn as sns

apc.mpl.setup()

df = sns.load_dataset("titanic")
sns.violinplot(data=df, x="age", y="class", inner="box")
```

### Default seaborn
(commenting out `apc.mpl.setup()`)

![6e18b3c1-02b7-4151-a458-25806f20d168](https://github.com/user-attachments/assets/9f104fd3-050e-4029-850f-bde9c26d6815)

### arcadia_pycolor formatting

![6c4cbda5-aef6-4e50-8046-42acffd75a90](https://github.com/user-attachments/assets/c27ec763-3a95-431a-8146-6132bbdf8d52)

**Comment by mezarque** [comment]
Thanks for letting us know about this issue! It seems like this is a result of us setting the `patch.linewidth` parameter in `matplotlib.rc_context` to `0`. Per the style guide, patches on figures (bar plots, violin plots, etc.) should not have a surrounding stroke. I think `seaborn` seems to use this parameter to globally set some plot features, such as the inner bar of a `sns.violinplot`.

For now, you can get around this default by wrapping function calls in a `with` statement like follows...

```python
import arcadia_pycolor as apc
import seaborn as sns
import matplotlib as mpl

apc.mpl.setup()

with mpl.rc_context({"patch.linewidth": 1}):
    df = sns.load_dataset("titanic")
    sns.violinplot(data=df, x="age", y="class", inner="box")
```
![image](https://github.com/user-attachments/assets/960826a9-94d3-4d5c-bedd-c9ae70a5f674)


...or by adding the `linewidth` attribute to your violin plot call with a non-zero value:

```python
import arcadia_pycolor as apc
import seaborn as sns

apc.mpl.setup()

df = sns.load_dataset("titanic")
sns.violinplot(data=df, x="age", y="class", inner="box", linewidth=1)
```

![image](https://github.com/user-attachments/assets/e4f68199-1ec3-4bd2-9da1-363573066d2f)

I can look more into how you can remove the stroke just on the violin shape without affecting the ability to see the box plot.

**Comment by mezarque** [comment]
After some digging, it does seem like all of the `sns.violinplot` inner plots are affected by the default setting. You should be able to make them appear using the `inner_kws` argument. Here are the parameters you can modify to restore the inner plots for each of the different inner plotting types:


## Inner box plots
```python
import arcadia_pycolor as apc
import seaborn as sns
import matplotlib.pyplot as plt

apc.mpl.setup()

df = sns.load_dataset("titanic")
sns.violinplot(
    data=df,
    x="age",
    y="class",
    inner="box",
    inner_kws={
        "box_width": 5,
        "color": "apc:dusk",
    }
)
```
![image](https://github.com/user-attachments/assets/c8e7a1e3-dc1c-4350-ae05-d86c966dd297)

## Inner box plots (whisker only)
```python
sns.violinplot(
    data=df,
    x="age",
    y="class",
    inner="box",
    inner_kws={
        "whis_width": 2,
        "color": apc.dusk,
    }
)
```
![image](https://github.com/user-attachments/assets/becab1a6-98b7-450b-a076-60898fd6b8f0)

## Quartile plot
```python
sns.violinplot(
    data=df,
    x="age",
    y="class",
    inner="quart",
    inner_kws={
        "linewidth": 1.5,
        "color": "apc:dusk",
    }
)
```
![image](https://github.com/user-attachments/assets/1f7bb3f1-3005-4e5a-951a-8e6905593e5c)

## Stick plot
```python
sns.violinplot(
    data=df,
    x="age",
    y="class",
    inner="stick",
    inner_kws={
        "linewidth": 0.5,
        "color": "apc:lapis",
    }
)
```
![image](https://github.com/user-attachments/assets/cb92233e-31d8-4635-aabf-7a76d7561e9e)

## Point plot
```python
sns.violinplot(
    data=df,
    x="age",
    y="class",
    inner="point",
    inner_kws={
        "marker": ".",
        "s": 15,
        "color": "apc:dusk",
    }
)
```
![image](https://github.com/user-attachments/assets/c6bbd300-ec10-4578-912e-1c843e7bf156)

**Comment by lanery** [comment]
Thanks for the in-depth digging @mezarque !
