### ISSUE TITLE
Add ability to save figure as multiple filetypes simultaneously

### ISSUE THREAD

**Issue by reillyowencooper** [Arcadia-Science/arcadia-pycolor#49]
I often want to save a .pdf and .png file for each figure I make, which results in a lot of duplicate lines of code where the only thing I've changed is the extension. It would be great to have an option in `save_figure` that allows you to save both filetypes (or more, if people use other extensions) at the same time. Something like:

```
def save_figure(fname: str, fname_types: list = ["pdf, png"], context: str = "web", **savefig_kwargs: dict[Any, Any]) -> None:
    "Save the current figure with the default settings for web."
    kwargs = SAVEFIG_KWARGS_WEB if context == "web" else SAVEFIG_KWARGS_PRINT
    kwargs.update(**savefig_kwargs)  # type: ignore
    for fname_type in fname_types:
        plt.savefig(fname = fname + fname_type, **kwargs) #type: ignore
```

**Comment by mezarque** [comment]
Addressed by #51
